### PR TITLE
Feature / update comment error message

### PR DESCRIPTION
**Pull request by sbrody**
Changes markup for comment error messages in line with update to 4.0. Can be tested once [this PR](https://github.com/dxw/govuk-blogs/pull/160) has been approved.

### CODE REVIEW

**Comment by RobjS** [comment]
@sbrody Do you know how I can trigger this markup to appear in the frontend?

**Comment by sbrody** [comment]
> @sbrody Do you know how I can trigger this markup to appear in the frontend?

Sorry - yes should have added some testing notes. Go to a single blog post and attempt to comment with an empty message and you will see the error markup.

**Comment by sbrody** [comment]
@RobjS I've rebased in the changes setting jQuery as a dependency. On doing that I discovered a couple more errors in the JavaScript caused by improper use of $ - which I have also fixed here as they are related to the commenting issue.

**Comment by RobjS** [comment]
@sbrody I'm a bit unsure what's happening here! Before you pushed the new changes, I couldn't get the errors to trigger, though I'm not sure why. But with the new changes you've pushed, I can get them to trigger even *without* the changes from `$` to `jQuery`.

i.e. if I do `git checkout 6930d` to get just your first commit, then run `yarn run grunt` to re-compile the JS, the errors still work. So I think the `$`/`jQuery` change might be a red herring?

**Comment by sbrody** [comment]
> @sbrody I'm a bit unsure what's happening here! Before you pushed the new changes, I couldn't get the errors to trigger, though I'm not sure why. But with the new changes you've pushed, I can get them to trigger even _without_ the changes from `$` to `jQuery`.
> 
> i.e. if I do `git checkout 6930d` to get just your first commit, then run `yarn run grunt` to re-compile the JS, the errors still work. So I think the `$`/`jQuery` change might be a red herring?

@RobjS yes - the errors are displaying but are you not getting the console error, which prevents the error summary box above from appearing? (Although not related to the update, I thought it was worth fixing at the same time - shall I separate it out into another PR?)

**Review by RobjS — APPROVED** [review]
Ah, that all makes sense now! LGTM 👍

**Pull request merged**
