### PR TITLE
Feature/search bar styling

### PR DESCRIPTION
**Pull request by sbrody**
Updates search bar styling to more closely match that found on the main gov.uk sites. Also fixes a styling bug which pushed the search button onto a second line at certain screen sizes.

The styling changes are made manually because the .gem-xxx classes on the gov.uk site are not available as part of the general govuk-frontend.

Note: I have kept the search bar at 40px height rather than 50px as currently it only spans the sidebar width rather than the full site width on gov.uk and I thought it looked a bit odd at that height.

image

### CODE REVIEW

**Review by matthewpassmore — CHANGES_REQUESTED** [review]
This is looking good. A few points (referencing [the search form](https://www.gov.uk/search?q=)):

- The search icon is different from GOV.UK. Can we use their icon?
- For improved accessibility, let's remove the placeholder and make the label visible. The label should be reworded to something more useful e.g. 'Search blog'.
- As per the GOV.UK form, there are a couple of additional attributes we can add to the search input markup; `enterkeyhint`, `title`.

**Comment by sbrody** [comment]
> This is looking good. A few points (referencing [the search form](https://www.gov.uk/search?q=)):
> 
>     * The search icon is different from GOV.UK. Can we use their icon?
> 
>     * For improved accessibility, let's remove the placeholder and make the label visible. The label should be reworded to something more useful e.g. 'Search blog'.
> 
>     * As per the GOV.UK form, there are a couple of additional attributes we can add to the search input markup; `enterkeyhint`, `title`.

All makes sense - the latest commit should include all these changes

**Comment by matthewpassmore** [comment]
The label looks a little visually disconnected from the input beneath. Can we tighten the spacing? The label currently has padding and a margin, whereas the GOV.UK version just has a bottom margin of `10px`.

**Comment by sbrody** [comment]
> The label looks a little visually disconnected from the input beneath. Can we tighten the spacing? The label currently has padding and a margin, whereas the GOV.UK version just has a bottom margin of `10px`.

Good point - have amended

**Review by matthewpassmore — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
