### PR TITLE
Feature/29 list block styling

### PR DESCRIPTION
**Pull request by sbrody**
List elements already apply the default GOV.UK styling. However there is an additional 'spaced' styling specified in the [documentation](https://design-system.service.gov.uk/styles/lists/), which this PR adds.

To test, add a list element and select the 'Extra spacing' style and check that the extra spacing is applied.

image

### CODE REVIEW

**Review by matthewpassmore — COMMENTED** [review]
I'm not seeing the style variation options, for this or any other block?

**Comment by matthewpassmore** [comment]
Worth us tightening up the space for top-level list items that follow-on from nested list items:

Screenshot 2024-04-04 at 16 38 48

**Comment by sbrody** [comment]
> I'm not seeing the style variation options, for this or any other block?

That is a mystery - do you not see this when the list block is selected? 
Screenshot 2024-04-04 at 16 50 50

**Comment by sbrody** [comment]
> Worth us tightening up the space for top-level list items that follow-on from nested list items:
> Screenshot 2024-04-04 at 16 38 48

Good spot - that should now be done

**Review by matthewpassmore — APPROVED** [review]
It was a caching issue preventing the variations from showing. All sorted.

Looks good to me 👍

**Pull request merged**
