### PR TITLE
Feature / update site logo

### PR DESCRIPTION
**Pull request by sbrody**
Adds new markup for gov.uk logo svg, as per govuk-frontend 5.0.

Before:
image

After:
image

### CODE REVIEW

**Comment by RobjS** [comment]
@sbrody The current one is actually the correct one since v5.1 see https://github.com/alphagov/govuk-frontend/releases/tag/v5.1.0?utm_source=GOV.%E2%80%8CUK+Design+System&utm_campaign=aabdb157a5-FRONTEND_CROWN_05022024&utm_medium=email&utm_term=0_367f0a5723-aabdb157a5-589329769. (I think of it as "Sunken cupcake = old crown, risen cupcake = new crown"). It's probably worth confirming that our implementation matches what they suggest in the 5.1 changelog, but if so then we won't need to change anything here.

**Comment by sbrody** [comment]
> @sbrody The current one is actually the correct one since v5.1 see https://github.com/alphagov/govuk-frontend/releases/tag/v5.1.0?utm_source=GOV.%E2%80%8CUK+Design+System&utm_campaign=aabdb157a5-FRONTEND_CROWN_05022024&utm_medium=email&utm_term=0_367f0a5723-aabdb157a5-589329769. (I think of it as "Sunken cupcake = old crown, risen cupcake = new crown"). It's probably worth confirming that our implementation matches what they suggest in the 5.1 changelog, but if so then we won't need to change anything here.

Ah ok - I didn't spot that - I have updated the PR as the structure of the markup has also been changed

**Review by RobjS — APPROVED** [review]
LGTM 👍 Looks like this also does the removal of the fallback image that https://github.com/dxw/govuk-blogs/pull/166 does?

**Comment by sbrody** [comment]
> LGTM 👍 Looks like this also does the removal of the fallback image that #166 does?

Yes - will delete that PR

**Pull request merged**
