### PR TITLE
Feature/10 Yellow focused links 

### PR DESCRIPTION
**Pull request by mingoland**
## Trello card URL:
https://trello.com/c/X4OMpZBj/10-yellow-focused-links-dont-have-enough-contrast-with-the-white-or-grey-background

## Changes in this PR:
- Add the new focus style from Design System
- Adjust padding of page navigator for the black bottom outline
- Prevent Gov.uk logo from new focus style

### Before
Screenshot 2019-12-10 at 12 16 39

### After
Screenshot 2019-12-10 at 12 16 33

### Before
Screenshot 2019-12-10 at 12 17 27

### After
Screenshot 2019-12-10 at 12 17 22

### Before
Screenshot 2019-12-10 at 12 17 51

### After
Screenshot 2019-12-10 at 12 17 41

### Before
Screenshot 2019-12-10 at 12 29 13

### After
Screenshot 2019-12-10 at 12 28 27

### CODE REVIEW

**Comment by RobjS** [comment]
@mingoland This is all working for me, but I wonder if the new link focus states have wider implications. For instance, the black line is often overlapping onto the text below when I'm testing locally:

From the list of latest blogs on the central homepage:

Screenshot 2019-12-10 at 15 18 37

From an individual blog entry:

Screenshot 2019-12-10 at 15 18 23

Do we need to increase the line height generally? Or reduce the size of the black underline?

**Comment by mingoland** [comment]
New changes:
- Remove the original underline when focus on
- Change to black text when focus on 

### Before 
Screenshot 2019-12-11 at 11 12 17


### After
Screenshot 2019-12-11 at 11 12 29

**Comment by RobjS** [comment]
@mingoland This looks good to me. Please could you update the changelog (CHANGELOG.md) to include these changes? You can put them in an "unreleased" section for now - e.g. above the line ```## [2.5.0] — 2019-12-10```, you could add something like:

```
## Unreleased

### Changed
- Link focus style updated to reflect Gov.uk design system
```

But feel free to amend that text as you see fit!

The changelog convention we follow is documented here: https://keepachangelog.com/en/1.0.0/

**Comment by mingoland** [comment]
Hi @RobjS it's updated. Please see if it's ok.

**Pull request merged**
