### PR TITLE
Chore / Remove Modernizr

### PR DESCRIPTION
**Pull request by sbrody**
The version of Modernizr installed was last updated in 2012. There have been a number of breaking changes since. In addition, govuk-frontend 5.0 does not support polyfills for IE so Modernizr seems redundant.

### CODE REVIEW

**Comment by RobjS** [comment]
@sbrody I think this needs a rebase on top of the latest version of `develop`, I'm seeing a Bowser error at the moment.

**Comment by sbrody** [comment]
> @sbrody I think this needs a rebase on top of the latest version of `develop`, I'm seeing a Bowser error at the moment.

I think the issue is another dependency of Bowser, which is dealt with in this PR https://github.com/dxw/govuk-blogs/pull/172. I'm not quite sure why that didn't come up when I removed Bowser - but sorry this is getting more complicated

**Comment by sbrody** [comment]
> If I checkout this branch then do `git rebase origin/main` locally, it seems to fix the issue. So I think a rebase and recompile to fix the merge conflicts that come up during the rebase might fix it?

Ok - I've pushed the rebased version but it's still showing the error for me

**Comment by RobjS** [comment]
@sbrody Have you run `yarn run grunt` as part of the rebase? When I initially pull this branch I'm seeing the error, but after another `yarn run grunt` run it disappears.

**Comment by sbrody** [comment]
> @sbrody Have you run `yarn run grunt` as part of the rebase? When I initially pull this branch I'm seeing the error, but after another `yarn run grunt` run it disappears.

Ok thanks - that works now - it just needed to rebuild so the whole Bowser issue could be separated out...

**Review by RobjS — APPROVED** [review]
LGTM - probably worth squashing these commits together.

**Pull request merged**
