### PR TITLE
Feature/503 migrate single template to govuk frontend

### PR DESCRIPTION
**Pull request by RobjS**
Migrates the template for displaying a single post, and associated partials (including comments form) to govuk frontend.

Before: 
2020-04-14-16-41-localhost

After:
2020-04-14-16-49-localhost

### CODE REVIEW

**Comment by calumryan** [comment]
@RobjS one other spot see class name `govuk-body-s tags`  this adds a 20 pixel bottom margin. The existing tags paragraph has a 30 pixel bottom margin.

**Comment by xlthlx** [comment]
@calumryan could you please review the code change? Thank you

**Comment by RobjS** [comment]
@xlthlx I think the commit history has gone a bit wonky, I'm seeing a lot of commits that weren't originally from this branch. 

The commits in the PR should be 8996dc5, a319633, 94b72db plus your extra commits.

**Comment by xlthlx** [comment]
@RobjS could you please check if now is it all good? Thanks

**Comment by RobjS** [comment]
@xlthlx It looks like all he changes are wrapped up into one commit now. I think that commit includes all the changes that were required for this card, so that should be ok, but it'd be good to update the commit message so it talks about all the changes, rather than just the footer. Please also include a link to the relevant Trello card: https://trello.com/c/ULTbZzEi/503-template-to-migrate-singlephp

**Comment by calumryan** [comment]
> @calumryan could you please review the code change? Thank you

@xlthlx looks fine now

**Pull request merged**
